name: Frontend tests

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Ng test run
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run test
      - name: Cypress run
        uses: cypress-io/github-action@v5.6.1 # use the explicit version number
        with:
          build: npm run build
          start: npm start
