name: Frontend tests

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Ng test run
        with:
          build: npm run build
          start: npm run test
      - name: Cypress run
        uses: cypress-io/github-action@v5.6.1 # use the explicit version number
        with:
          build: npm run build
          start: npm start
