name: Frontend tests

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

        
    steps:
      - uses: actions/checkout@v3
      - name: Run Karma Tests
        uses: ahmedrizwan/angular-karma-test-action@v1.0.8
      - name: Cypress run
        uses: cypress-io/github-action@v5.6.1 # use the explicit version number
        with:
          build: npm run build
          start: npm start
